### ISSUE TITLE
How to get PHASE file from a vcf file?

### ISSUE THREAD

**Issue by SC-Duan** [bredelings/BayesianEstimatorSelfing#1]
Hi,
How to get PHASE file from a vcf file?
Thank you!

**Comment by bredelings** [comment]
Hi, could you provide me with an example vcf file?
One approach would be to add the ability to read VCF directly.  Another approach would be to convert the VCF file to a phase file.

**Comment by SC-Duan** [comment]
Hi,
Here is the instruction of VCF 4.1 (http://www.internationalgenome.org/wiki/Analysis/Variant%20Call%20Format/vcf-variant-call-format-version-41).
Then I convert this file to a fastPHASE format as below,
vcftools --vcf my.vcf --plink --out my.plink
plink -file my.plink --recode fastphase-1chr --out my.plink.fastphase
and I adjust the fastphase file using a custom script,  finally, I get a file like :

123       #sample size
283      SNP number
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS          #283 SNPs
1-2     T       T       A       A                    #sample1 genotype, two alleles
10-2    NA      NA      NA      NA      NA      NA      #sample2 genotype, two alleles, NA, missing
100     C       C       A       A        #sample3genotype, two alleles

however, this file can not work.
Can you give me some help?
Thank you!

**Comment by bredelings** [comment]
I think I see the problem.  I need to change the C++ code to handle S loci, which have values like A,T,G,C in addition to M loci, which have values like 4, 10, 23.

**Comment by SC-Duan** [comment]
Thank you!

**Comment by bredelings** [comment]
For SNP loci, I'm wondering if there is something more natural than `NA` to represent missing data.  Maybe `-` or `N`?  What do you think?

Related to this, you write that you "adjust the fastphase file using a custom script".  What adjustments are required?  I ask because maybe I could make some changes to read the fastphase output directly (assuming it is not too hard to implement).

**Comment by SC-Duan** [comment]
Yes, it can be N, ? or -9 for  missing data.
The PLINK fastPHASE file likes this,

123                                                                                                                #sample size
283                                                                                                               #SNP number
P 60464 60539 60546 60645 60703 60704 60710 60725 60782      #SNP position
\# ID 1-2                                                                                                        #sample ID
TACCACAGGAACCGGAACCAACAAAAGT                                                 #genotype 
TACCACAGGAACCGGAACCAACAAAAGT                                                 #genotype 
\# ID 10-2                                                                                                       #sample ID
?????????????????????????????????                                                   #genotype 
?????????????????????????????????                                                   #genotype

**Comment by bredelings** [comment]
OK, I'm looking into implementing this.  I'd like to preserve the ability to include microsatellite sites.  I might make some improvements along the way.

The P line made me think: the software assumes that all the loci are unlinked.  Are your loci unlinked?

**Comment by bredelings** [comment]
I'm making progress, but am not done yet.

I was wondering if your data comes from whole-genome sequencing, or perhaps from RAD sequencing.  In the case of RAD sequencing, you could possibly code each RAD locus as a single allele.

**Comment by SC-Duan** [comment]
Hi,
1. My loci are linked, but I can filter the loci and get unlinked loci. 
2. My data comes from whole-genome sequencing.

**Comment by bredelings** [comment]
Hi, if you use the git master versions of bali-phy and BES, then this works now.
The function `read_phase2_file` handles the format for PHASE 2, where the existing `read_phase_file` function handles the format for PHASE version 1.

I've created a module `Generic2` in addition to `Generic` that uses the new format, but in general I'd recommend modifying one of the *.hs files and using that directly.

**Comment by bredelings** [comment]
I think this issue is addressed by the 0.1.3 release.  Is there anything that remains to be done?
